### PR TITLE
Migrations for auto test deploy

### PR DESCRIPTION
**Pull request by hughescr**
These commits clean things up and make it possible to do automated testing & builds.  Right now, it's test-only, but I can configure it to automatically deploy from certain branches if they pass tests, etc.  There is no auto-deployment yet.

 part of cognoa/cognoa#1303

### CODE REVIEW

**Comment by hughescr** [comment]
You can see an example of the auto-build/test that happens by looking at the "LambCI" messages in #devbots in Slack, eg:

https://cognoa.slack.com/archives/devbots/p1487292901000050

**Comment by fgarberson** [comment]
Just having a look at this now. My guess from what I am reading here is that the automated testing will check for any exceptions that are thrown by either the unit tests or the regression tests. As of right now the regression tests do not throw an exception when they fail. They instead produce .csv outputs comparing results with expectations, and the user needs to briefly scan them by eye to see if they look reasonable. If we want to use this path then I think it would make sense to add an additional layer to the regression tests that compares the outputs in some key aspects and throws an exception if it fails to find agreement within reasonable tolerance.

**Comment by mrhalim2001** [comment]
This isn’t necessarily an all-or-nothing kind of thing. We can for example start by making the most important unit tests throw an exception upon failure. That would be a good start. Later we can expand progressively and eventually include regression tests.

-Halim

On Mon, Feb 27, 2017 at 4:55 PM fgarberson

<
mailto:fgarberson <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

Just having a look at this now. My guess from what I am reading here is that the automated testing will check for any exceptions that are thrown by either the unit tests or the regression tests. As of right now the regression tests do not throw an exception when they fail. They instead produce .csv outputs comparing results with expectations, and the user needs to briefly scan them by eye to see if they look reasonable. If we want to use this path then I think it would make sense to add an additional layer to the regression tests that compares the outputs in some key aspects and throws an exception if it fails to find agreement within reasonable tolerance.

—

You are receiving this because your review was requested.

Reply to this email directly,
https://github.com/cognoa/cognoa-tbb-lambda/pull/4#issuecomment-282906999
, or

**Comment by hughescr** [comment]
What "test failure" means is that the shell exit status will be non-zero when running
```
python unit_test.py && python regression_test.py
```
on the host under test.  It's up to you guys when you want those to exit with a non-zero status.  Right now, it's when any of the asserts fail in the unit tests, but yes I think the regression tests don't actually signal their pass/fail status out to the caller in an automated way.

**Comment by hughescr** [comment]
Here's example output from the automated run: https://lambci-buildresults-lr2p0t4vk1ic.s3.amazonaws.com/gh/cognoa/cognoa-tbb-lambda/builds/6/ceec72ab6d4811557fb32054445a4d25.html

**Pull request merged**
